spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todoapp?useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngochuymail25@gmail.com
    password: uytp msqg otvs gjjm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
api:
  prefix: api
jwt:
  expiration: 25920000
  secretKey: EQOIAUgMdB/GxPmYT+uew/HLvOkYDOrAo3ihcFynD+Y=