spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todoapp?useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

api:
  prefix: api
jwt:
  expiration: 25920000
  secretKey: EQOIAUgMdB/GxPmYT+uew/HLvOkYDOrAo3ihcFynD+Y=